### ISSUE TITLE
Are there parts that could use glutin?

### ISSUE THREAD

**Issue by jdm** [servo/surfman#31]
#30 made me think that maybe it's time to consolidate and focus on the pieces of this repo that don't make sense in glutin.

**Comment by emilio** [comment]
Glutin might want to reuse our glx backend instead of relying on OsMesa (which was the main reason we needed to create it). 

We'll need to access the context internals to integrate it with layers though, though this could be worked out.

Other than that, this repo IMHO should be responsible for:
- Integrating with rust-layers.
- Detection of gl context capabilities needed for WebGL (max uniforms, vertex, texture size, and a long etc...)
- Detection of gl features (based on the gl API version and probably availability of extensions), to make possible to have WebGL extensions.

I could have missed something more but...

**Comment by emilio** [comment]
Pinging @tomaka and @glennw

**Comment by tomaka** [comment]
Using a glx pixel buffer is definitely something that I'd like to do in glutin. It's just that it's not implemented.

OSMesa was implemented first because it's available on travis.

**Comment by emilio** [comment]
Yes, we have the same problem here, the tests are disabled on linux (https://github.com/ecoal95/rust-offscreen-rendering-context/blob/master/.travis.yml#L24).

I can port it to glutin if you want, maybe CircleCI has support for it?

**Comment by atouchet** [comment]
This repo no longer uses Glutin. Is this issue still relevant?

**Comment by jdm** [comment]
Nope.
